---
name: Update PRs to main

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

permissions:
  contents: "write"

jobs:
  update-prs:
    runs-on: "ubuntu-20.04"
    steps:
      -
        uses: "actions/checkout@v4"
        with:
          fetch-depth: "0"  # Fetch alllll the branches
          persist-credentials: false  # TODO See if this means a subsequent push will use credentials that trigger PR tests...

      - run: "./update-prs.sh"
        env:
          GH_TOKEN: ${{ github.token }}
